-- ============================================================================
-- File: 02_create_tables.sql
-- Description: Creates all application tables with optimized indexes
-- ============================================================================

-- Incoming Message Table
CREATE TABLE INCOMING_MESSAGE_TABLE (
    MSG_ID                NUMBER(16,0) NOT NULL,
    SOURCE                VARCHAR2(100) NOT NULL,
    X_CORRELATION_ID      VARCHAR2(200) NOT NULL,
    INTERNAL_SOURCE_ID    NUMBER(16,0) NOT NULL,
    FINAL_STATUS          VARCHAR2(50),
    INTERNAL_STATUS       VARCHAR2(200),
    PHASE                 VARCHAR2(50),
    EVENT_TYPE            VARCHAR2(100),
    PROCESS_TYPE          VARCHAR2(100),
    ERROR_MESSAGE         VARCHAR2(2000),
    CYCLE_DATE            DATE NOT NULL,
    ATTRIBUTE_KEY1        VARCHAR2(500),
    ATTRIBUTE_KEY2        VARCHAR2(500),
    ATTRIBUTE_KEY3        VARCHAR2(500),
    ATTRIBUTE_KEY4        VARCHAR2(500),
    ORIGINAL_MSG          CLOB NOT NULL,
    TRANSFORMED_MSG       CLOB,
    PROCESS_LOG           CLOB,
    INSERT_TIMESTAMP      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIMESTAMP      TIMESTAMP,
    INSERTED_BY           VARCHAR2(100) NOT NULL,
    UPDATED_BY            VARCHAR2(100),
    PRIORITY              NUMBER(2,0) DEFAULT 5,
    RETRY_COUNT           NUMBER(3,0) DEFAULT 0,
    CONSTRAINT PK_INCOMING_MESSAGE PRIMARY KEY (X_CORRELATION_ID, SOURCE),
    CONSTRAINT UQ_INCOMING_MSG_ID UNIQUE (MSG_ID)
) PARTITION BY RANGE (CYCLE_DATE) 
INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
(
    PARTITION P_INITIAL VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD'))
);

-- Outgoing Message Table
CREATE TABLE OUTGOING_MESSAGE_TABLE (
    MSG_ID                NUMBER(16,0) NOT NULL,
    SOURCE                VARCHAR2(100) NOT NULL,
    X_CORRELATION_ID      VARCHAR2(200) NOT NULL,
    INTERNAL_SOURCE_ID    NUMBER(16,0) NOT NULL,
    OUTGOING_MSG_ID       VARCHAR2(200) NOT NULL,
    FINAL_STATUS          VARCHAR2(50),
    PHASE                 VARCHAR2(50),
    ERROR_MESSAGE         VARCHAR2(2000),
    EVENT_TYPE            VARCHAR2(100),
    PROCESS_TYPE          VARCHAR2(100),
    CYCLE_DATE            DATE NOT NULL,
    ATTRIBUTE_KEY1        VARCHAR2(500),
    ATTRIBUTE_KEY2        VARCHAR2(500),
    ATTRIBUTE_KEY3        VARCHAR2(500),
    ATTRIBUTE_KEY4        VARCHAR2(500),
    ORIGINAL_MSG          CLOB,
    PROCESS_LOG           CLOB,
    INSERT_TIMESTAMP      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIMESTAMP      TIMESTAMP,
    INSERTED_BY           VARCHAR2(100) NOT NULL,
    UPDATED_BY            VARCHAR2(100),
    RETRY_COUNT           NUMBER(3,0) DEFAULT 0,
    CONSTRAINT PK_OUTGOING_MESSAGE PRIMARY KEY (X_CORRELATION_ID, SOURCE, OUTGOING_MSG_ID),
    CONSTRAINT UQ_OUTGOING_MSG_ID UNIQUE (MSG_ID)
) PARTITION BY RANGE (CYCLE_DATE)
INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
(
    PARTITION P_INITIAL VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD'))
);

-- Duplicate Message Table
CREATE TABLE DUPLICATE_MESSAGE_TABLE (
    ID                    NUMBER(16,0) NOT NULL,
    SOURCE                VARCHAR2(100) NOT NULL,
    X_CORRELATION_ID      VARCHAR2(200) NOT NULL,
    MESSAGE_HASHCODE      VARCHAR2(500),
    DUPLICATE_TYPE        VARCHAR2(50),
    ORIGINAL_MSG_ID       NUMBER(16,0),
    DUPLICATE_MSG_ID      NUMBER(16,0),
    DETAILS               CLOB,
    DETECTED_TIMESTAMP    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DETECTED_BY           VARCHAR2(100),
    CONSTRAINT PK_DUPLICATE_MESSAGE PRIMARY KEY (ID)
);

-- Process Lock Table
CREATE TABLE PROCESS_LOCK_TABLE (
    LOCK_NAME             VARCHAR2(100) NOT NULL,
    LOCKED_BY             VARCHAR2(200),
    LOCK_STATUS           VARCHAR2(20),
    LOCK_ACQUIRED_TIME    TIMESTAMP DEFAULT SYSTIMESTAMP,
    LOCK_UPDATED_TIME     TIMESTAMP,
    LOCK_EXPIRY_TIME      TIMESTAMP,
    VERSION               NUMBER(10,0) DEFAULT 0,
    CONSTRAINT PK_PROCESS_LOCK PRIMARY KEY (LOCK_NAME)
);

COMMIT;
