-- ============================================================================
-- File: 03_create_indexes_v2.sql
-- Description: ENHANCED indexes including instance tracking
-- ============================================================================

-- Instance Registry Indexes
CREATE INDEX IDX_INSTANCE_STATUS ON INSTANCE_REGISTRY_TABLE(INSTANCE_STATUS);
CREATE INDEX IDX_INSTANCE_HEARTBEAT ON INSTANCE_REGISTRY_TABLE(LAST_HEARTBEAT);

-- Incoming Message Table Indexes
CREATE INDEX IDX_INCOMING_MSG_ID ON INCOMING_MESSAGE_TABLE(MSG_ID);
CREATE INDEX IDX_INCOMING_STATUS ON INCOMING_MESSAGE_TABLE(FINAL_STATUS, INTERNAL_STATUS);
CREATE INDEX IDX_INCOMING_CYCLE_DATE ON INCOMING_MESSAGE_TABLE(CYCLE_DATE);
CREATE INDEX IDX_INCOMING_SOURCE ON INCOMING_MESSAGE_TABLE(SOURCE);
CREATE INDEX IDX_INCOMING_HASHCODE ON INCOMING_MESSAGE_TABLE(ATTRIBUTE_KEY4);
CREATE INDEX IDX_INCOMING_INSERT_TS ON INCOMING_MESSAGE_TABLE(INSERT_TIMESTAMP);

-- NEW INDEXES FOR AUTOLOADER QUERIES
CREATE INDEX IDX_INCOMING_LEASE_EXPIRY ON INCOMING_MESSAGE_TABLE(LEASE_EXPIRY_TIMESTAMP);
CREATE INDEX IDX_INCOMING_INSTANCE_ID ON INCOMING_MESSAGE_TABLE(PROCESSING_INSTANCE_ID);
CREATE INDEX IDX_INCOMING_PROC_STARTED ON INCOMING_MESSAGE_TABLE(PROCESSING_STARTED_TIMESTAMP);

-- Composite index for orphan detection
CREATE INDEX IDX_INCOMING_ORPHAN_DETECTION ON INCOMING_MESSAGE_TABLE(
    INTERNAL_STATUS, LEASE_EXPIRY_TIMESTAMP, PROCESSING_INSTANCE_ID
);

-- Outgoing Message Table Indexes (unchanged)
CREATE INDEX IDX_OUTGOING_MSG_ID ON OUTGOING_MESSAGE_TABLE(MSG_ID);
CREATE INDEX IDX_OUTGOING_INTERNAL_SRC ON OUTGOING_MESSAGE_TABLE(INTERNAL_SOURCE_ID);
CREATE INDEX IDX_OUTGOING_STATUS ON OUTGOING_MESSAGE_TABLE(FINAL_STATUS);
CREATE INDEX IDX_OUTGOING_CYCLE_DATE ON OUTGOING_MESSAGE_TABLE(CYCLE_DATE);
CREATE INDEX IDX_OUTGOING_HASHCODE ON OUTGOING_MESSAGE_TABLE(ATTRIBUTE_KEY4);

-- Duplicate Message Table Indexes
CREATE INDEX IDX_DUP_CORRELATION ON DUPLICATE_MESSAGE_TABLE(X_CORRELATION_ID, SOURCE);
CREATE INDEX IDX_DUP_HASHCODE ON DUPLICATE_MESSAGE_TABLE(MESSAGE_HASHCODE);
CREATE INDEX IDX_DUP_TIMESTAMP ON DUPLICATE_MESSAGE_TABLE(DETECTED_TIMESTAMP);

-- Process Lock Table Indexes
CREATE INDEX IDX_LOCK_STATUS ON PROCESS_LOCK_TABLE(LOCK_STATUS);

COMMIT;
